# NumPy basics

## Numpy arrays

In [1]:
import numpy as np

In [2]:
# python list to numpy array
pylist1 = [1,2,3,3]

In [3]:
type(pylist1)

list

In [6]:
n_arr = np.array(pylist1)

In [7]:
type(n_arr)

numpy.ndarray

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
my_m1 = [[[1,2],[3,4]],[[4,5],[6,7]],[[1,4],[5,2]]]

In [12]:
my_m1

[[[1, 2], [3, 4]], [[4, 5], [6, 7]], [[1, 4], [5, 2]]]

In [13]:
np.array(my_m1)

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]],

       [[1, 4],
        [5, 2]]])

In [15]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [16]:
np.zeros(3)   #in floating

array([0., 0., 0.])

In [19]:
np.zeros((2,5,3,4))  #n-dimensions

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.linspace(0,10,3)  # 3 equi spaced points, includes last number also, length = 3

array([ 0.,  5., 10.])

In [28]:
# from normal dist.
np.random.randn(2,3)

array([[ 0.82254491, -1.22084365,  0.2088636 ],
       [-1.95967012, -1.32818605,  0.19686124]])

In [29]:
# from uniform dist. gets a numbr from [0,1) 
np.random.rand(5)

array([0.96958463, 0.77513282, 0.93949894, 0.89482735, 0.59789998])

In [30]:
np.random.randint(0,10,3)

array([7, 6, 8])

In [25]:
# put these in one cell
#Seed random
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [37]:
arr = np.arange(0,36)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [40]:
arr.reshape(3,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [41]:
arr.max()

35

In [42]:
arr.min()

0

In [43]:
#to get index location of max element
arr.argmax()

35

In [45]:
arr.dtype

dtype('int32')

In [46]:
arr.shape

(36,)

# Slicing

In [49]:
a1 = np.arange(0,10,1)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a1[:3]

array([0, 1, 2])

In [51]:
a1[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
a1[3:]

array([3, 4, 5, 6, 7, 8, 9])

### Broadcasting means

In [55]:
# you can't do this normal python list
a1[:3]=999
a1

array([999, 999, 999,   3,   4,   5,   6,   7,   8,   9])

In [61]:
# Be careful, if you make changes to the slice it will affect the original array
# Better make a copy

a2 = a1[:3]
a2

array([123, 123, 123])

In [62]:
a2[:]=123
a2

array([123, 123, 123])

In [63]:
# affected original array
a1

array([123, 123, 123,   3,   4,   5,   6,   7,   8,   9])

In [66]:
arr_2d = np.array([[5,10,12],[12,23,12],[23,44,22]])
arr_2d

array([[ 5, 10, 12],
       [12, 23, 12],
       [23, 44, 22]])

In [67]:
arr_2d.shape


(3, 3)

In [68]:
arr_2d[2]

array([23, 44, 22])

In [69]:
# array[row,col]
arr_2d[1,2]   #we can use arr_2d[1][2]

12

In [71]:
#slicing
#arr_2d[1:,1:]

array([[23, 12],
       [44, 22]])

In [72]:
#array is created by numpy
a1

array([123, 123, 123,   3,   4,   5,   6,   7,   8,   9])

In [75]:
#Broadcasting using condition
bool_ar = a1 > 100

In [76]:
bool_ar

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [81]:
a1[bool_ar]

array([123, 123, 123])

In [82]:
#Directly we can do by
a1[a1>100]


array([123, 123, 123])

## Numpy operations
can be extended to pandas


In [83]:
arr1 = np.arange(0,10)**2
arr1

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [84]:
np.sqrt(arr1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [85]:
np.sin(arr1)

array([ 0.        ,  0.84147098, -0.7568025 ,  0.41211849, -0.28790332,
       -0.13235175, -0.99177885, -0.95375265,  0.92002604, -0.62988799])

In [86]:
np.log(arr1)

C:\Users\JONATHAN\AppData\Local\Temp/ipykernel_27764/2108464003.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr1)


array([      -inf, 0.        , 1.38629436, 2.19722458, 2.77258872,
       3.21887582, 3.58351894, 3.8918203 , 4.15888308, 4.39444915])

In [87]:
arr1.std()

26.852374196707448

In [88]:
arr.mean()

17.5

In [91]:
arr2d = np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [92]:
arr2d.sum()

300

In [93]:
arr2d.sum(axis=0)  #sums across rows i.e sums the columns total

array([50, 55, 60, 65, 70])

In [94]:
arr2d.sum(axis=1)  #sums across columns i.e sums the rows total

array([ 10,  35,  60,  85, 110])

## Numpy exercise

In [95]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [96]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [97]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [98]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [99]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [102]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [105]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [134]:
np.random.rand(1)

array([0.84891382])

In [108]:
np.random.randn(25)

array([ 0.47319325,  0.6591906 ,  2.34074633,  1.07098519,  0.09641648,
        0.41910211, -0.95302779, -1.0478706 , -1.87567677, -1.36678214,
        0.63630511, -0.90672067,  0.47604259,  1.30366127,  0.21158701,
        0.59704465, -0.89633518, -0.11198782,  1.46894129, -1.12389833,
        0.9500054 ,  1.72651647,  0.45788508, -1.68428738,  0.32684522])

In [110]:
np.arange(16,26).reshape(2,5)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [114]:
np.arange(.01,1.01,.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [115]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [116]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [117]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [118]:
mat[3,4]

20

In [128]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [129]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [130]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [131]:
mat.sum()

325

In [132]:
mat.std()

7.211102550927978

In [133]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])